### ISSUE TITLE
Electronic circuit

### ISSUE THREAD

**Issue by Daniellagace** [LieBtrau/arduino-as3933#7]
I'm interest in your project but I don't find an electronic circuit for an 125khz antenna with an AS3933. Do you have one?

**Comment by LieBtrau** [comment]
I never finished this project because I realized later on that Bluetooth Low Energy is a better option for my application:
* greater range
* low power transmitter (versus lots of power needed for 125kHz signal generator)
* two way communication
* encrypted communication
* cheaper dev. modules (AS3933 is quite expensive)
* enables direct interaction with smartphone (as they have bluetooth built-in).

I think there's little application for this LF-technology.  Maybe tire-pressure-monitoring systems (TPMS).  What else?  BTW, Digikey is discontinuing the AS3933.

If you want to persist in playing with the AS3933, I suggest you to have a look at the manual for the  [evaluation kit](http://www1.futureelectronics.com/doc/AUSTRIAMICROSYSTEMS/AS3933_AN01_DemoboardDescr_v1%5B1%5D.pdf).

If you make your own PCB for the AS3933, I suggest to remain as close as possible to the original design.  Don't repeat my mistakes.
