### ISSUE TITLE
Using EM4095

### ISSUE THREAD

**Issue by bakosaleima** [LieBtrau/arduino-as3933#9]
In according to you, could the EM4095 be used instead of AS3933 as wake up signal for rfid application? And what about RDM6300

**Comment by LieBtrau** [comment]
Hi Bakosaleima,
The EM4095 and RDM6300 are RFID-readers.  These readers generate an LF-field and require lots of power to do so.
The AS3933 behaves more like an RFID-tag.  It requires the energy of the RFID-reader to wakeup.  
So : no, the EM4095 and RDM6300 can not be used instead of the AS3933.

**Comment by bakosaleima** [comment]
thank you for the quick answer, I didn't undestand whether the rdm6300 couldn't be used because of range or hardware incompatibilities? The signal is on 125khz both rdm and as39 work on the same frequency, I don't care about power or range, so theoretically could the rdm receive the signal as it is and resend it?

**Comment by LieBtrau** [comment]
You could use the RDM6300 or EM4095 to wake-up an AS3933.

I stopped developing the AS3933 because I think Bluetooth Low Energy (BLE) is a better fit for most applications:
* AS3933 is expensive
* AS3933 range is limited
* AS3933 requires fairly large (and expensive) antenna
* AS3933 itself might be low-power, but it requires a high power transmitter.
* AS3933 is RX only.  It can't send data back to the base station.
* AS3933 requires an external microcontroller, which further adds to cost and PCB-area.
* AS3933 is not secure.  Any device that generates the correct waveform will wake it up.

All these are disadvantages that a BLE-device (e.g. nRF52840) doesn't have and it doesn't consume much more power.

If your application really requires RFID (e.g. for scanning items as they pass through a gate), you're probably better off with 13.56MHz vicinity cards/ICs (ISO/IEC 15693).

**Comment by bakosaleima** [comment]
Wow, such a precise answer thank you so much! Anyway I would like to complete my work with rfid 125khz. My final question is this: will the rdm6300 work as well as as3933 in reading/sending wake up signal? If no do you know of any other arduino compatible device that can solve my problem?

**Comment by LieBtrau** [comment]
You could try to use the RDM6300 to generate the 125kHz field to wake up the AS3933.  As the RDM6300 probably can't modulate the LF-field, you can't use the MSK-pattern matching of the AS3933.  The AS3933 will wake-up when it receives any 125kHz signal, probably leading to a lot of false wake-up events.
